### ISSUE TITLE
Create Curated Courier 1.0 release

### ISSUE THREAD

**Issue by aibakeneko** [inidun/curated_courier#4]
Create release with additional files as stated in the article draft.

**Comment by aibakeneko** [comment]
@benjamingmartin, @fredrik1984, @roger-mahler, @o-martin: I have created a release and added additional files: https://github.com/inidun/curated_courier/releases/tag/0.3.

Please update the release description and add the remaining `Quality control files` and the `Courier metadata file` when and if you can.

Feel free to update the repository description (the `README.md`-file) as well.

**Comment by fredrik1984** [comment]
Listed below are the quality control file links. I have done some changes in column namnes to make it more clear. 

@aibakeneko Not sure in which format you want these files, but I guess you can upload them as Excel och CSV

https://docs.google.com/spreadsheets/d/1lpDSSKP28m0OHa--UH7mAznj-NN8deRrBIQLN0vyNPI/edit#gid=0

https://docs.google.com/spreadsheets/d/1Z40M5FqTLceO8tttw6L87P6fEMvUmQSfeJ4xczDDUto/edit#gid=0

**Comment by aibakeneko** [comment]
Added quality control files to [release](https://github.com/inidun/curated_courier/releases/tag/0.3). Removed PDF link column. Added PDF filename column instead. Uploaded files in CSV-format.

**Comment by aibakeneko** [comment]
OK to add metadata file. Ref #7.

**Comment by aibakeneko** [comment]
Added [UNESCO_Courier_metadata.xlsx](https://github.com/inidun/inidun_data/blob/ac2cfef94138b9cb44a39c2791261153e4275ea8/original/UNESCO_Courier_metadata.xlsx).

_Originally posted by @aibakeneko in https://github.com/inidun/curated_courier/issues/7#issuecomment-1697460034_
